#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    # Write your code here
    # 4 6 5 3 3 1
    # 1 3 3 4 5 6
    # 3
    a.sort()
    res =0
    tem =0
    cnt =0
    for i in range(len(a)-1) :
        for j in range(i,len(a)) :

            if( abs(a[i] - a[j] ) <=1):
                print(a[i], a[j], tem , '@')
                tem +=1
            else :
                print(a[i], a[j], tem , '!')
                if(res < tem ) :
                    res = tem
                tem =0
                cnt +=1
    if (cnt ==0) :
        res =len(a)
    return res
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
