#!/bin/python3

import math
import os
import random
import re
import sys



# Complete the beautifulDays function below.
def beautifulDays(i, j, k):
    resCnt =0

    for d in range (i, j+1) :
        if( (d- int(str(d)[::-1])) %k  ==0) :
            resCnt +=1
    return resCnt

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ijk = input().split()

    i = int(ijk[0])

    j = int(ijk[1])

    k = int(ijk[2])

    result = beautifulDays(i, j, k)

    fptr.write(str(result) + '\n')

    fptr.close()
