#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the viralAdvertising function below.
def viralAdvertising(n):

    res = 0
    sh = 5
    lk =0
    for i in range(n):
             
        lk = math.floor(sh /2)
        res = res+lk
        print("end", sh, lk,res)
        sh = lk*3

    return res


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()
